package lt.vu.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @return the value of PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRICE
     *
     * @param price the value for PUBLIC.PRODUCT.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}