package lt.vu.mybatis.model;

import java.util.Date;

public class UserOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER_ORDER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER_ORDER.ORDERED_AT
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Date orderedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER_ORDER.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER_ORDER.USER_ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Integer userId;

    private User user;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER_ORDER.ID
     *
     * @return the value of PUBLIC.USER_ORDER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER_ORDER.ID
     *
     * @param id the value for PUBLIC.USER_ORDER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER_ORDER.ORDERED_AT
     *
     * @return the value of PUBLIC.USER_ORDER.ORDERED_AT
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Date getOrderedAt() {
        return orderedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER_ORDER.ORDERED_AT
     *
     * @param orderedAt the value for PUBLIC.USER_ORDER.ORDERED_AT
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setOrderedAt(Date orderedAt) {
        this.orderedAt = orderedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER_ORDER.PRICE
     *
     * @return the value of PUBLIC.USER_ORDER.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER_ORDER.PRICE
     *
     * @param price the value for PUBLIC.USER_ORDER.PRICE
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER_ORDER.USER_ID
     *
     * @return the value of PUBLIC.USER_ORDER.USER_ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER_ORDER.USER_ID
     *
     * @param userId the value for PUBLIC.USER_ORDER.USER_ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}