package lt.vu.mybatis.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.EMAIL
     *
     * @return the value of PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.EMAIL
     *
     * @param email the value for PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.NAME
     *
     * @return the value of PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.NAME
     *
     * @param name the value for PUBLIC.USER.NAME
     *
     * @mbg.generated Tue May 24 09:27:38 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}